### ISSUE TITLE
Suggestion: Always focus on open a note in edit-mode / always focus on change from view-mode to edit-mode / alway focus  in split mode

### ISSUE THREAD

**Issue by merlinuwe** [usysrc/obsidian-text-focus-plugin#1]
Thanks for your great plugin.

Is it possible to 

- _always_ focus the note when it is openend in edit mode,
- when I switch from view-mode to edit-mode and
- when a note is opened in split mode?

This would be very useful.

**Comment by tilhars** [comment]
Thank you for the suggestions. The plugin made with the focus of new notes in mind. Split mode would be great to support. I don't know about switching. Where would for example be the cursor when opening it?

**Comment by merlinuwe** [comment]
I switch with <strg-e> from view to edit mode.

The cursor (caret) should be on the top, on the bottom or on the last place it was.

**Comment by tilhars** [comment]
You probably mean toggling off reading view. That would be a good use case indeed!

**Comment by tilhars** [comment]
The latest release includes "Automatically focuses the text area when toggling read mode to source mode.". Please update the plugin in obsidian.

**Comment by merlinuwe** [comment]
Works on Windows 10. Thank you very much for this feature! ;-)
